### ISSUE TITLE
Quartz configuration

### ISSUE THREAD

**Issue by RLejolivet** [blossom-project/blossom#130]
Most likely since the migration to using spring-boot-starter-quartz, quartz.properties are not (all ?) taken into account anymore.

Notably, the `threadPool.threadCount = 10` is not effective, reverting to the default of 1 thread.

**Comment by RLejolivet** [comment]
Managed to get multiple threads again with the following configuration: 

```yaml
spring:
  quartz:
    properties:
      org.quartz.threadPool.class: org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor
      org.quartz.threadPool.threadCount: 10
```
